### ISSUE TITLE
[Feature]: convert F_parm to log(F_parm)

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-ost/ss3-source-code#401]
### Describe the solution you would like.

F_parm logically cannot be < 0.0, but if catch for a fleet * time is very small, it can get close to 0.0 and impede convergence.

F_parm is used only in Procedure_Section to populate Hrate which is the F value used in calculations:
            Hrate(f, t) = F_rate(g);

so easy to change this to:
            Hrate(f, t) = exp(F_rate(g));

requires associated changes to the bounds on the F_rate parameter.
should do the same for the init_F parameters.

### Describe alternatives you have considered

none considered

### Statistical validity, if applicable

implementing parameters in log space is generally recommended by my statistician colleagues

### Describe if this is needed for a management application

no

**Comment by Rick-Methot-NOAA** [comment]
@Cole-Monnahan-NOAA 
I'm interested in your opinion on this change.  It is nearly completed.

**Comment by Cole-Monnahan-NOAA** [comment]
@Rick-Methot-NOAA does this actually change the model behavior when you have a really small catch? I'm generally skeptical of this for two reasons. 

First, ADMB's bounding functions will, I believe, closely mimic a `exp` transformation if you use bounds (0,Z) where Z is some large number. So I wouldn't expect it to actually change behavior close to 0, and thus it's not clear why it's needed. One advantage of the default ADMB transformation is that it behaves better when the parameter estimate is *very* close to the bound. By that I mean that the Hessian remains invertible whereas a logistic transformation will fail. Some see this as a good thing, because it lets the user leave parameter estimation on when the mode is at a bound. If you had a logistic transformation (e.g., `-hbf`) then the user would have to turn off estimation to get uncertainty. So if anything I'd expect worse performance a priori, meaning you'd have more models failing to do the SD calcs. It may be worth testing the models w/ the `hbf` flag too.

Second, the new approach is now a double transformation which makes it harder to interpret. I don't think ADMB will choke on it or anything, but it's not "clean" in some sense. I think ADMB should produce a .std file for unbounded parameters, see e.g., https://github.com/admb-project/admb/issues/275, and such an approach would not work here.

I'm a pragmatist though, so if this improves model convergence then I'd find that compelling evidence, if a bit unexpected.

**Comment by Rick-Methot-NOAA** [comment]
That was always my logic on this also.  Other community members have advocated for parameters being in log-space.  Here it is common for many F values to be near the natural lower of zero.  Your improvements of ADMB now flag that condition.  I will do a run in which I compare parameter variances with and without the log(F) approach.

**Comment by Cole-Monnahan-NOAA** [comment]
I see, yeah that may be an unintended consequence of the new output. I've seen it as well and just ignored it.

I did a quick test this AM. Here's the R code

````
### Quick exploration of the bounding options in ADMB
a <- 0 # min bound
b <- 2 # max bound
## this is the ADMB default, note input range is (-1,1)
f1 <- function(x) a+(b-a)*(.5*sin(x*pi/2)+.5)
## invoked with '-hbf' flag, standard logistic, input (-Inf,Inf)
f2 <- function(x) a+(b-a)/(1+exp(-x))
## log transform, input (-Inf,Inf)
f3 <- function(x) exp(x)
x <- seq(-15,-1, len=1000)
## go from (-1,1) space to logit space so comparable
x2 <- -1+2/(1+exp(-x))
y1 <- f1(x2)
y2 <- f2(x)
y3 <- f3(x)
plot(x, y1, type='l', log='y', ylab='Bounded value',
     xlab='Unbounded value')
lines(x, y2, col=2)
lines(x, y3, col=3)
legend('bottomright', legend=c('sine', 'logistic', 'log'),
       col=1:3, lty=1)
````

Which results in this plot
![image](https://github.com/nmfs-ost/ss3-source-code/assets/58868176/f18b9da7-b180-4eb0-8333-ad71675ded50)

Note the y-axis is in log space. So you can see that log and logistic approach the lower bound at the same rate just with an offset that depends on the max bound. The sine transform (default in ADMB) is very different.

**Comment by Rick-Methot-NOAA** [comment]
I ran a test using the petrale sole west coast assessment.  It has 2 fleets and a long time series, so the model needed to calculate very small F's going back to 1910.

I ran three model configurations:
1.  F as "hybrid F" which does not use F parameters and instead scales each F value to match the catch
2. F as a parameter with the parameter being the F value
3. F as exp(Fparm) in a trial branch.

The results are practically indistinguishable to many sig. digits between the runs.  I asked for F at age 10 as a derived quantity.  The se of this was the same no matter what method was used to produce the F values.  Similarly for derived quantities affected by F, like SSB.

I conclude that there is no value in converting to log(F) as the parameter, nor in providing users the option.

QED.

**Comment by Cole-Monnahan-NOAA** [comment]
Agreed, and that makes sense to me. A good experiment to do to confirm.

**Comment by iantaylor-NOAA** [comment]
Thanks for going through all this trouble @Rick-Methot-NOAA and @Cole-Monnahan-NOAA.
This type of exploration seems like the ideal process to figure out lots of potential model features for SS3 and any future model, so you've set a great example here.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Ian.  I think it good to summarize this in a paragraph for the next release notes.
