### ISSUE TITLE
create system to provide parameter types and minmax bounds

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ss3-source-code#73]
Imported from redmine, Issue [#77270](https://vlab.ncep.noaa.gov/redmine/issues/77270)
 Opened by @iantaylor-NOAA on 2020-04-01
Status when imported: New
 
The issue that Dan Fu reported (files attached to #77268) was caused by use_dev = 1 values for the Spline_Knot parameters. The user manual notes "These must be held constant (not estimated, e.g., negative phase value) during a model run" but it would be good to check for either positive phase or use_dev > 0 and exit with a warning.

I think I could figure out how to do this in SS_readcontrol_324.tpl and SS_readcontrol_330.tpl by following logic similar to that under "check on conversion of retention parameter". However, perhaps this should be done in a more comprehensive way to check any selectivity parameters which should not be estimated, such as the bin range parameters for Pattern = 5.

@richard.methot, feel free to assign to me with any guidance you have if you prefer that I tackle this.

**Comment by Rick-Methot-NOAA** [comment]
The issue here is that in SS_readcontrol, the code only knows what each parameter does when it is assigning parameter names.  And it creates those names in a code section that precedes the reading of the parameter lines.  When code does other things (like phase checks), it does so generically for all parameters.

So the fix would be to create a new vector containing an element for each parameter and assign that element a value that flags whether or not that parameter can be estimated.  It should also be possible to assign at the same time a logical min and max for the parameter.

There is a start to this already in the code.  Look at the quantities Parm_info and Parm_minmax in SS_global and in SS_readcontrol.
This is very incomplete implementation.

**Comment by Rick-Methot-NOAA** [comment]
[SS3_parmlabels.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8121437/SS3_parmlabels.txt)

**Comment by iantaylor-NOAA** [comment]
I took a quick look at the spreadsheet of ParmLabels and categorized 47 of the 216 entries. I think it won't be too hard to fill in the rest if we chip away little by little.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Ian.  Please add additional categories as needed.

**Comment by iantaylor-NOAA** [comment]
The FIMS project is developing a system for creating default parameter values as well as using parameter transformations to avoid the use of bounds. I would suggest applying the "wont-fix" and "FIMS" labels and closing this issue. 

The Google Sheet linked above https://docs.google.com/spreadsheets/d/1VwSeSziSD2dy-umRKMM5lc5h52QJbZ8qCwT4n8sPgqU/edit#gid=0 listing all SS3 parameter labels (prior to appending things like fleet name or number) may be useful as a reference for future work even though we didn't get very far in the categorization of those parameters and didn't yet come up with any default initial values.

Tagging @Bai-Li-NOAA who is doing lots of the coding to set up the system for providing FIMS defaults.
